In [5]:
# 1d array slicing:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
# 1. Slice specific range of elements (from index 1 to 4, exclusive)
slice1 = arr[1:4]
# 2. Slice from the beginning to a specific index
slice2 = arr[:5]
# 3. Slice from a specific index to the end
slice3 = arr[2:]
# 4. Slice with a step of 2
slice4 = arr[0:5:2]
# 5. Slice using negative indices
slice5 = arr[-5:-1]
# 6. Reverse the array using slicing
slice6 = arr[::-1]
# Print all the slices
print("Original Array:", arr)
print("Slice 1 :", slice1)
print("Slice 2 :", slice2)
print("Slice 3 :", slice3)
print("Slice 4 :", slice4)
print("Slice 5 :", slice5)
print("Slice 6 :", slice6)

Original Array: [10 20 30 40 50 60 70]
Slice 1 : [20 30 40]
Slice 2 : [10 20 30 40 50]
Slice 3 : [30 40 50 60 70]
Slice 4 : [10 30 50]
Slice 5 : [30 40 50 60]
Slice 6 : [70 60 50 40 30 20 10]


In [7]:
# 2d array slicing:
import numpy as np
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
# 1. Slice a submatrix (rows 1 to 2 and columns 2 to 3)
slice1 = arr[1:3, 2:4]
# 2. Slice all rows and specific columns (columns 1 to 3)
slice2 = arr[:, 1:3]
# 3. Slice specific rows and all columns (rows 1 to 2)
slice3 = arr[1:3, :]
# 4. Slice with a step (every 2nd row and every 2nd column)
slice4 = arr[::2, ::2]
# 5. Reverse the order of rows and columns
slice5 = arr[::-1, ::-1]
# 6. Extract a single row (row 2)
slice6 = arr[2, :]
# 7. Extract a single column (column 3)
slice7 = arr[:, 3]
# Print all slices
print("Original Array:", arr)
print("Slice 1:", slice1)
print("Slice 2:", slice2)
print("Slice 3:", slice3)
print("Slice 4:", slice4)
print("Slice 5:", slice5)
print("Slice 6:", slice6)
print("Slice 7:", slice7)

Original Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Slice 1: [[ 7  8]
 [11 12]]
Slice 2: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
Slice 3: [[ 5  6  7  8]
 [ 9 10 11 12]]
Slice 4: [[ 1  3]
 [ 9 11]]
Slice 5: [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Slice 6: [ 9 10 11 12]
Slice 7: [ 4  8 12 16]
